# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:

  push: {}

  release:
    types: [created]

jobs:
  quality:
    name: Code QA
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install -y pandoc # Needed by sphinx for notebooks
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.1

  checks:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10"]

    name: Python  ${{ matrix.python-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        pip install pytest
        pip install -e .[all]
        pip install -r tests/requirements.txt
        pip freeze

    - name: Tests
      run: pytest

  notify-failure:
    if: failure()
    runs-on: ubuntu-latest
    needs: [quality, checks]
    name: Notify failure
    steps:
      - uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI_F }}
          # notification-summary: ${{ steps.qa.outputs.status }}
          notification-summary: ❌ Build failed on anemoi.datasets!
          notification-color: dc3545
          timezone: Europe/Paris
          verbose-logging: true

  notify-success:
    if: success()
    runs-on: ubuntu-latest
    needs: [quality, checks]
    name: Notify success
    steps:
      - uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI_F }}
          # notification-summary: ${{ steps.qa.outputs.status }}
          notification-summary: ✅ New commit on anemoi.datasets
          notification-color: 17a2b8
          timezone: Europe/Paris
          verbose-logging: true

  deploy:

    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: [checks, quality]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Check that tag version matches code version
      run: |
        tag=${GITHUB_REF#refs/tags/}
        version=$(python setup.py --version)
        echo 'tag='$tag
        echo "version file="$version
        test "$tag" == "$version"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py sdist
        twine upload dist/*
