# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  quality:
    if: ${{ !contains(github.repository, 'private') }}
    uses: ecmwf-actions/reusable-workflows/.github/workflows/qa-precommit-run.yml@v2
    with:
      skip-hooks: "no-commit-to-branch"

  checks:
    uses: ecmwf-actions/reusable-workflows/.github/workflows/qa-pytest-pyproject.yml@v2
    with:
      python-version: "3.9"

  deploy:
    needs: [checks, quality]
    uses: ecmwf-actions/reusable-workflows/.github/workflows/cd-pypi.yml@v2
    secrets: inherit
